apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: WebApplication
spec:
  selector:
    matchLabels:
      app: LoginWebApp Maven Webapp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: LoginWebApp Maven Webapp
    spec:
      containers:
        - name: LoginWebApp Maven Webapp
          image: aryandvn24/samplewebapp # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: LoginWebApp Maven Webapp
spec:
  selector:
    app: LoginWebApp Maven Webapp
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.